/// Flutter icons AppIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData exit = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData promocode = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playstation = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData referal = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tariff = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
